version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: sciscope_db
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: sciscope_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
