version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  test-node:
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
      DB_HOST: db
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $TEST_DB_NAME
    docker:
      - image: cimg/node:16.17
      - image: cimg/postgres:15.1
        name: db
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: $TEST_DB_NAME
          POSTGRES_HOST_AUTH_METHOD: md5
    steps:
      - checkout

      - run:
          name: Debug Postgres Environment Variables (Hex & Normal)
          command: |
            echo "POSTGRES_USER (normal): $POSTGRES_USER"
            echo -n "POSTGRES_USER (hex): "; echo -n "$POSTGRES_USER" | xxd

            echo "POSTGRES_PASSWORD (normal): $POSTGRES_PASSWORD"
            echo -n "POSTGRES_PASSWORD (hex): "; echo -n "$POSTGRES_PASSWORD" | xxd

            echo "POSTGRES_DB (normal): $POSTGRES_DB"
            echo -n "POSTGRES_DB (hex): "; echo -n "$POSTGRES_DB" | xxd

      - run:
          name: Restart Postgres if Needed
          command: docker restart db || true

      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            for i in {1..30}; do
              nc -z db 5432 && echo "Postgres is ready" && exit 0
              echo "Waiting for Postgres..."
              sleep 1
            done
            echo "Postgres failed to start" && exit 1

      - run:
          name: Verify Postgres Users
          command: |
            psql -h db -U postgres -d "$TEST_DB_NAME" -c '\du'

      - run:
          name: Run Database Migrations
          command: npx knex migrate:latest --env test --knexfile ./src/config/knexfile.js

      - run:
          name: Run Tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit

      - store_test_results:
          path: ./test-results/

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

workflows:
  build-and-test:
    jobs:
      - test-node
