version: 2.1

jobs:
  build:
    docker:
      - image: img/node:14.21.3
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: $TEST_DB_NAME
          DB_HOST: $DB_HOST
          DB_PORT: $DB_PORT
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Wait for PostgreSQL to be ready
          command: |
            for i in $(seq 1 10); do
              nc -z localhost 5432 && echo "Postgres is up" && exit 0;
              echo "Waiting for Postgres to start...";
              sleep 2;
            done;
            echo "Postgres did not start in time";
            exit 1

      - run:
          name: Run Migrations
          command: npx knex migrate:latest --knexfile ./src/config/knexfile.js

      - run:
          name: Run Tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
