version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-node:
    docker:
      - image: circleci/node:14.17.0
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

      # Wait for PostgreSQL to be ready before running migrations
      - run:
          name: Wait for PostgreSQL
          command: |
            for i in $(seq 1 10); do
              nc -z 127.0.0.1 5432 && echo "Postgres is up" && exit 0;
              echo "Waiting for Postgres...";
              sleep 2;
            done;
            echo "Postgres did not start in time";
            exit 1

      # Run Knex Migrations
      - run:
          name: Run Migrations
          command: npx knex migrate:latest --knexfile ./src/config/knexfile.js

      # Install jest-junit for test reporting
      - run:
          command: npm install jest-junit

      # Run tests
      - run:
          name: Run Tests
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit

      # Store test results
      - store_test_results:
          path: ./test-results/

workflows:
  build-and-test:
    jobs:
      - test-node
